# Generated by Django 5.0.6 on 2024-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg_id', models.IntegerField()),
                ('seg_img', models.ImageField(upload_to='segmentation_images/')),
            ],
        ),
    ]
